# Generated by Django 4.1.2 on 2022-10-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='name1',
        ),
        migrations.RemoveField(
            model_name='income',
            name='name2',
        ),
        migrations.AlterField(
            model_name='income',
            name='income2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12),
        ),
    ]
