# Generated by Django 4.1.2 on 2022-10-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_remove_income_name1_remove_income_name2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='income2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
