# Generated by Django 4.1.2 on 2022-10-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_alter_income_income2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='income1',
            new_name='income_1',
        ),
        migrations.RenameField(
            model_name='income',
            old_name='income2',
            new_name='income_2',
        ),
        migrations.AddField(
            model_name='income',
            name='reason_1',
            field=models.CharField(choices=[('blank', 'Blank'), ('social', 'Social'), ('salary', 'Salary'), ('donation', 'Donation')], default='blank', max_length=20),
        ),
        migrations.AddField(
            model_name='income',
            name='reason_2',
            field=models.CharField(choices=[('blank', 'Blank'), ('social', 'Social'), ('salary', 'Salary'), ('donation', 'Donation')], default='blank', max_length=100),
        ),
    ]
