# Generated by Django 4.1.2 on 2022-10-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_rename_income1_income_income_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='reason_1',
            new_name='reason_income',
        ),
        migrations.RemoveField(
            model_name='income',
            name='income_1',
        ),
        migrations.RemoveField(
            model_name='income',
            name='income_2',
        ),
        migrations.RemoveField(
            model_name='income',
            name='reason_2',
        ),
        migrations.AddField(
            model_name='income',
            name='income',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
