# Generated by Django 4.1.2 on 2022-10-16 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_rename_reason_1_income_reason_income_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='currency',
            field=models.CharField(choices=[('pln', 'PLN'), ('euro', 'EURO'), ('gbp', 'GBP'), ('usd', 'USD')], default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='income',
            name='reason_income',
            field=models.CharField(choices=[('blank', 'Blank'), ('social', 'Social'), ('salary', 'Salary'), ('donation', 'Donation')], default='', max_length=15),
        ),
    ]
