# Generated by Django 4.1.2 on 2022-10-16 16:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_income_currency_alter_income_reason_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='date_income',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='income',
            name='currency',
            field=models.CharField(choices=[('PLN', 'PLN'), ('€', 'EURO'), ('£', 'GBP'), ('$', 'USD')], default='', max_length=5),
        ),
    ]
