# Generated by Django 4.1.2 on 2022-10-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_income_date_income_alter_income_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='date_income',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
