# Generated by Django 4.1.2 on 2022-10-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0012_expensesinfo_reason_expenses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensesinfo',
            name='reason_expenses',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Food', 'Food'), ('Fuel', 'Fuel'), ('Entertainment', 'Entertainment'), ('Other', 'Other')], default='', max_length=50),
        ),
    ]
