# Generated by Django 4.1.2 on 2022-10-31 19:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0014_remove_expensesinfo_reason_expenses_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expensesinfo',
            old_name='expense_name',
            new_name='expense_reason',
        ),
        migrations.AlterField(
            model_name='expensesinfo',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2022, 10, 31, 19, 33, 40, 326517, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='date_income',
            field=models.DateField(default=datetime.datetime(2022, 10, 31, 19, 33, 40, 325517, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='reason_income',
            field=models.CharField(choices=[('Blank', 'Blank'), ('Social', 'Social'), ('Salary', 'Salary'), ('Donation', 'Donation')], default='', max_length=15),
        ),
    ]
