# Generated by Django 4.1.2 on 2022-10-31 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0018_alter_expensesinfo_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensesinfo',
            name='expense_reason',
            field=models.CharField(blank=True, choices=[('Rent', 'Rent'), ('Food', 'Food'), ('Fuel', 'Fuel'), ('Entertainment', 'Entertainment'), ('Other', 'Other')], max_length=50),
        ),
    ]
