# Generated by Django 4.1.2 on 2022-10-31 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0019_alter_expensesinfo_expense_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='reason_income',
            field=models.CharField(blank=True, choices=[('Social', 'Social'), ('Salary', 'Salary'), ('Donation', 'Donation')], max_length=15),
        ),
    ]
