# Generated by Django 4.1.2 on 2022-10-31 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0020_alter_income_reason_income'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expensesinfo',
            old_name='user_expense',
            new_name='author_expanse',
        ),
    ]
