# Generated by Django 4.1.2 on 2022-10-31 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0021_rename_user_expense_expensesinfo_author_expanse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='reason_income',
            field=models.CharField(blank=True, choices=[('Salary', 'Salary'), ('Social', 'Social'), ('Donation', 'Donation'), ('Other', 'Other')], max_length=15),
        ),
    ]
