# Generated by Django 4.1.2 on 2022-10-31 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0022_alter_income_reason_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensesinfo',
            name='currency_expanse',
            field=models.CharField(choices=[('PLN', 'PLN'), ('€', 'EURO'), ('£', 'GBP'), ('$', 'USD')], default='', max_length=5),
        ),
    ]
