# Generated by Django 4.1.2 on 2022-10-31 21:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0023_expensesinfo_currency_expanse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='date_income',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
    ]
