# Generated by Django 4.1.2 on 2022-10-31 21:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0026_alter_income_date_income'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expensesinfo',
            old_name='date_added',
            new_name='date_expanse',
        ),
        migrations.AlterField(
            model_name='income',
            name='date_income',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
