# Generated by Django 4.1.2 on 2022-10-31 22:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0027_rename_date_added_expensesinfo_date_expanse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='date_income',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date income "YYYY/MM/DD"'),
        ),
    ]
