# Generated by Django 4.1.2 on 2022-11-02 20:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0028_alter_income_date_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensesinfo',
            name='author_expanse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.income'),
        ),
        migrations.AlterField(
            model_name='expensesinfo',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Amount of expanse'),
        ),
        migrations.AlterField(
            model_name='expensesinfo',
            name='date_expanse',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date expanse ("YYYY-MM-DD")'),
        ),
        migrations.AlterField(
            model_name='income',
            name='date_income',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date income ("YYYY-MM-DD")'),
        ),
        migrations.AlterField(
            model_name='income',
            name='income',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Amount income'),
        ),
    ]
