# Generated by Django 4.1.2 on 2022-11-02 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budget', '0029_alter_expensesinfo_author_expanse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensesinfo',
            name='author_expanse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
