# Generated by Django 4.1.2 on 2022-11-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0031_alter_expensesinfo_expense_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensesinfo',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=2, verbose_name='Amount of expanse'),
        ),
    ]
