# Generated by Django 4.1.2 on 2022-11-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0036_remove_expensesinfo_currency_expanse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensesinfo',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Amount of expanse'),
        ),
        migrations.AlterField(
            model_name='income',
            name='income',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Amount income'),
        ),
    ]
