# Generated by Django 4.1.2 on 2022-11-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0037_alter_expensesinfo_cost_alter_income_income'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanYourExpenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_expanse', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='how much money you want to spend on...')),
                ('expense_reason', models.CharField(blank=True, choices=[('Rent', 'Rent'), ('Food', 'Food'), ('Fuel', 'Fuel'), ('Entertainment', 'Entertainment'), ('Other', 'Other'), ('Cosmetics and Chemicals', 'Cosmetics and Chemicals')], max_length=50)),
            ],
        ),
    ]
