# Generated by Django 4.1.2 on 2022-11-11 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0038_planyourexpenses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlanYourExpenses',
        ),
    ]
