# Generated by Django 4.1.3 on 2022-11-11 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0040_alter_expensesinfo_cost_alter_income_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensesinfo',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Amount of expanse'),
        ),
        migrations.AlterField(
            model_name='income',
            name='income',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Amount income'),
        ),
    ]
