# Generated by Django 4.1.3 on 2022-11-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0041_alter_expensesinfo_cost_alter_income_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensesinfo',
            name='expense_reason',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Food', 'Food'), ('Fuel', 'Fuel'), ('Entertainment', 'Entertainment'), ('Other', 'Other'), ('Cosmetics and Chemicals', 'Cosmetics and Chemicals')], max_length=50),
        ),
        migrations.AlterField(
            model_name='income',
            name='reason_income',
            field=models.CharField(choices=[('Salary', 'Salary'), ('Social', 'Social'), ('Donation', 'Donation'), ('Other', 'Other')], max_length=15),
        ),
    ]
