# Generated by Django 4.1.3 on 2022-11-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0042_alter_expensesinfo_expense_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensesinfo',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Amount of expanse'),
        ),
        migrations.AlterField(
            model_name='income',
            name='income',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Amount income'),
        ),
    ]
