# Generated by Django 4.1.3 on 2022-11-11 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0043_alter_expensesinfo_cost_alter_income_income'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanYourExpanses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum_expanses', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Sum of expanses')),
                ('expanse_plan_reason', models.ForeignKey(choices=[('Rent', 'Rent'), ('Food', 'Food'), ('Fuel', 'Fuel'), ('Entertainment', 'Entertainment'), ('Other', 'Other'), ('Cosmetics and Chemicals', 'Cosmetics and Chemicals')], on_delete=django.db.models.deletion.CASCADE, related_name='reason_expanse', to='budget.expensesinfo')),
            ],
        ),
    ]
