# Generated by Django 4.1.3 on 2022-11-11 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0045_planyourexpanses_amount_money_to_spent_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlanYourExpanses',
        ),
    ]
